# Generated by Django 4.1.2 on 2022-10-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('empresa', models.CharField(max_length=20)),
                ('valor', models.CharField(max_length=20)),
            ],
        ),
    ]
