# Generated by Django 4.1.2 on 2022-10-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feria_App', '0002_alter_cliente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productos', models.CharField(max_length=20)),
                ('precio', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField(max_length=10)),
                ('calidad', models.CharField(max_length=20)),
            ],
        ),
    ]
