# Generated by Django 4.1.2 on 2022-10-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feria_App', '0004_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('terminado', 'Terminado'), ('proceso', 'Proceso'), ('venta', 'Venta')], max_length=10),
        ),
    ]
