# Generated by Django 4.0.4 on 2022-10-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feria_App', '0005_alter_productos_estado'),
    ]

    """ operations = [
        migrations.CreateModel(
            name='Productos_venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('solicitud', models.CharField(max_length=200)),
                ('cierre_oferta', models.DateField()),
            ],
        ),
    ] """
