# Generated by Django 4.0.4 on 2022-10-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feria_App', '0008_productosventa_alter_productor_cantidad_and_more'),
    ]

    """ operations = [
        migrations.CreateModel(
            name='ProductosVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('solicitud', models.CharField(max_length=200)),
                ('cierre_oferta', models.DateField()),
                ('comuna', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='productor',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ] """
