# Generated by Django 4.0.4 on 2022-10-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feria_App', '0009_productosventa_alter_productor_cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('t_transporte', models.CharField(max_length=75)),
                ('comuna', models.CharField(max_length=75)),
            ],
        ),
    ]
