# Generated by Django 4.0.4 on 2022-12-01 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feria_App', '0013_productosventa_productosventaregistro_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductosVentaRegistro',
            new_name='ProductosRegistro',
        ),
    ]
