# Generated by Django 2.1.15 on 2022-12-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feria_App', '0018_transporte_capacidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productosregistro',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='productosregistro',
            name='oferta',
            field=models.IntegerField(),
        ),
    ]
