# Generated by Django 2.1.15 on 2022-12-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feria_App', '0019_auto_20221213_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosregistro',
            name='cantidad',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
